### ISSUE TITLE
Install OpalKelly Front-panel executable to make FPGA work, doesnt work with just mio install

### ISSUE THREAD

**Issue by hsemwal** [Aharoni-Lab/miniscope-io#81]
I set up miniscope-io through github, received the following error messages when I attempted running. 

**PS C:\Users\Sayum\PycharmProjects\PythonProject\.venv\Lib\site-packages> pdm run mio stream capture -c .\miniscope_io\data\config\MSUS.yml**
Process _fpga_recv:
Traceback (most recent call last):
  File ".\Python313\Lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File ".\Python\Python313\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\miniscope_io\stream_daq.py", line 323, in _fpga_recv
    dev = self._init_okdev(BIT_FILE)
  File ".\venv\Lib\site-packages\miniscope_io\stream_daq.py", line 262, in _init_okdev
    dev = okDev()
  File "\.venv\Lib\site-packages\miniscope_io\devices\opalkelly.py", line 30, in __init__
    raise DeviceOpenError(f"Cannot open device: {serial_id}")
miniscope_io.exceptions.DeviceOpenError: Cannot open device:

However, after I installed Frontpanel from Opalkelly, the FPGA now works. Does this mean that the .dll FPGA drivers did not properly install?

**Comment by sneakers-the-rat** [comment]
hmm hmm @MarcelMB / @t-sasatani do you also have to do this when you go to use the FPGA on a new machine?

**Comment by sneakers-the-rat** [comment]
We should print the error code there, that would be helpful for debugging lol

**Comment by sneakers-the-rat** [comment]
ok if i extract the windows .exe i find the driver files, but not using windows I don't know how to install them manually. We should

- vendor those files
  - `okuart.cat`
  - `okuart.inf`
  - `okusb.cat`
  - `okusb.inf`
  - `WdfCoInstaller01009.dll`
  - `WinUSBCoInstaller2.dll`
- create a wrapper script to install them. Looks like...
  -   `PnPUtil` for `.inf` - https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/pnputil-command-syntax
  - Looks like we just copy .dll's into system32 but that seems... bad. 
- detect when drivers have not been installed and prompt to do so

**Comment by t-sasatani** [comment]
>hmm hmm @MarcelMB / @t-sasatani do you also have to do this when you go to use the FPGA on a new machine?

@MarcelMB works on Mac, and I already had the front panel installed on my Windows PC for different reasons, so not sure if this was necessary. Eventually, it should be boxed, but I think we can just say install it from here for now, as we're the only users anyway.

**Comment by sneakers-the-rat** [comment]
Agreed - put it in the docs and leave this open as a los priority todo for now
